on:
  fork:
  push:
  issues:
    types: [ opened ]
  issue_comment:
    types: [ created ]
  pull_request_target:
    types: [ opened ]
  pull_request_review_comment:
    types: [ created ]

jobs:

  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: TawfikYasser/gh-actions-ty/src/welcome@v0.3 
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Issue-Header'
          pr-message: 'PR-Header'
          footer: 'Footer'
