on:
  fork:
  push:
  issues:
    types: [ opened ]
  issue_comment:
    types: [ created ]
  pull_request_target:
    types: [ opened ]
  pull_request_review_comment:
    types: [ created ]

jobs:

  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: TawfikYasser/gh-actions-ty/src/welcome@main 
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '<h1>Issue-Header</h1>'
          pr-message: '<h1>PR-Header</h1>'
          footer: '**Footer**'
